export const REQUEST_STATUSES = {
    SUCCESS: 'success',
    PENDING: 'pending',
    ERROR: 'error',
};

export const ORIGIN_CERT_STATUS = {
    VALID: 'valid',
    INVALID: 'invalid',
};

export const NOT_WORKING_STATES = {
    IS_INSTALLED: 'IS_INSTALLED',
    IS_RUNNING: 'IS_RUNNING',
    IS_PROTECTION_ENABLED: 'IS_PROTECTION_ENABLED',
    IS_APP_UP_TO_DATE: 'IS_APP_UP_TO_DATE',
    IS_EXTENSION_UPDATED: 'IS_EXTENSION_UPDATED',
    IS_RELOADING: 'IS_RELOADING',
};
