export const REQUEST_STATUSES = {
    SUCCESS: 'success',
    PENDING: 'pending',
    ERROR: 'error',
};

export const ORIGINAL_CERT_STATUS = {
    VALID: 'valid',
    INVALID: 'invalid',
};

export const WORKING_STATES = {
    IS_APP_INSTALLED: 'IS_APP_INSTALLED',
    IS_APP_RUNNING: 'IS_APP_RUNNING',
    IS_APP_UP_TO_DATE: 'IS_APP_UP_TO_DATE',
    IS_APP_SETUP_CORRECTLY: 'IS_APP_SETUP_CORRECTLY',
    IS_EXTENSION_UPDATED: 'IS_EXTENSION_UPDATED',
    IS_EXTENSION_RELOADING: 'IS_EXTENSION_RELOADING',
    IS_PROTECTION_ENABLED: 'IS_PROTECTION_ENABLED',
};

export const SWITCHER_IDS = {
    HTTPS_SWITCHER: 'https-switcher',
    GLOBAL_SWITCHER: 'global-switcher',
};
